sensors/urls.py
"""Django urls for the sensors app."""

from django.urls import path

from . import views

app_name = 'sensors'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='landing_index'),
    path('', views.SensorsList.as_view(), name='sensors_index'),
    path('<int:pk>/', views.SensorDetailView.as_view(), name='sensor_detail'),
    path('probe/', views.ProbesList.as_view(), name='probes_index'),
    # views for station
    path('station/', views.MeasuringStationList.as_view(), name='stations_index'),
    path('station/<int:pk>/', views.MeasuringStationDetailView.as_view(), name='station_detail'),
    path('station/<int:pk>/edit', views.MeasuringStationEditView.as_view(), name='station_update'),
    path('station/<int:pk>/delete/', views.MeasuringStationDeleteView.as_view(), name='station_delete'),
    path('station/add/', views.MeasuringStationCreateView.as_view(), name='station_create'),
]

sensors_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('sensors/', include('sensors.urls')),
    path('admin/', admin.site.urls),
]

sensors/models.py
"""Django models for the sensors app."""

from django.db import models


class ProbeDriver(models.Model):
    """Describe how probe drivers are structured.

    A probe driver describe the physical sensor and it's capacities.
    For multi sensors, such as the bme280, that outputs multiple variables,
    multiple probe sensors are created, one for each available measurement.
    """

    name = models.CharField('name of the driver', max_length=255,
                            primary_key=True)
    description = models.CharField('descripton of the driver', max_length=2048,
                                   blank=True)
    unit = models.CharField('measurement unit', max_length=255, blank=True)
    unit_symbol = models.CharField('symbol of the unit', max_length=255,
                                   blank=True)
    min_value = models.FloatField('lowest possible value', blank=True,
                                  null=True)
    max_value = models.FloatField('highest possible value', blank=True,
                                  null=True)

    def __str__(self):
        """Return a string representation of the object."""
        return self.name


class Sensor(models.Model):
    """Describe how Sensors are structured.

    A sensor in this context is when a probe driver is used with
    specific parameters set by the user. It is not about the generic sensor,
    but rather about how the user wants to collect it's data.
    """

    id = models.IntegerField(primary_key=True)
    name = models.CharField('user friendly name', max_length=255)
    description = models.CharField('description', max_length=2048, blank=True)
    probe_id = models.CharField('unique ID of the probe', max_length=1024,
                                default="0x00", blank=True)
    probe_driver = models.ForeignKey(ProbeDriver, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the object."""
        return self.name


class Measure(models.Model):
    """Describe how measures are structured.

    A measure is taken by a sensor of a defined type, and
    is saved in database, using the current timestamp at the
    time of insertion. The value is whatever the sensor returned.
    timestamp (ts) and the sensor id (sensor_id) are indexed for
    faster access times on reads.
    """

    id = models.AutoField(primary_key=True)
    sensor_id = models.ForeignKey(
                                  Sensor,
                                  on_delete=models.CASCADE,
                                  db_index=True
                                 )
    value = models.FloatField()
    ts = models.DateTimeField(db_index=True)

    def __str__(self):
        """Return a string representation of the object."""
        return "value: " + str(self.value)

    def was_published_recently(self):
        """Tell if the measure was saved in the last day."""
        return self.ts >= timezone.now() - datetime.timedelta(days=1)


class MeasuringStation(models.Model):
    """Describe how measuring stations are structured.

    A measuring station is a network device that have access to sensors,
    and periodically access those sensors to retrieve the values and store them
    into the database.
    """

    id = models.AutoField(primary_key=True)
    name = models.CharField('user friendly name', max_length=255)
    description = models.CharField('description', max_length=2048, blank=True)
    installed_sensors = models.ManyToManyField(Sensor)

    def __str__(self):
        """Return a string representation of the object."""
        return self.name

sensors/forms.py
from django import forms
from .models import Sensor, MeasuringStation


class AddMeasuringStationForm(forms.Form):
    station_name = forms.CharField(label='station name', max_length=255)
    station_description = forms.CharField(label='station description', max_length=255)
    installed_sensors = forms.ModelMultipleChoiceField(
            queryset=Sensor.objects,
            widget=forms.SelectMultiple,
            )


class EditMeasuringStationForm(forms.Form):
    # m = MeasuringStation.objects.get(id=station_id)
    station_name = forms.CharField(label='station name', max_length=255)
    station_description = forms.CharField(label='station description', max_length=255)
    installed_sensors = forms.ModelMultipleChoiceField(
            queryset=Sensor.objects,
            widget=forms.SelectMultiple,
            )

sensors/views.py
"""Django views for the sensors app."""

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Sensor, Measure, ProbeDriver, MeasuringStation
from django.utils import timezone
from .forms import AddMeasuringStationForm, EditMeasuringStationForm
from django.views.generic.edit import UpdateView, DeleteView, CreateView


class SensorsList(generic.ListView):
    """Show the list of saved sensors."""

    paginate_by = 10
    model = Sensor
    template_name = 'sensors/sensors_list.html'
    context_object_name = 'latest_sensor_list'

    def get_context_data(self, **kwargs):
        """Get the context for the view, generic."""
        context = super().get_context_data(**kwargs)
        context['sensors_count'] = Sensor.objects.all().count()
        return context

    def get_queryset(self):
        """Return the last 20 configured sensors."""
        return Sensor.objects.order_by('id')[:20]


class MeasuringStationList(generic.ListView):
    """Show the list of measuring stations."""

    paginate_by = 10
    model = MeasuringStation
    template_name = 'sensors/measuringstations_list.html'

    def get_context_data(self, **kwargs):
        """Get the context for the view, generic."""
        context = super().get_context_data(**kwargs)
        context['count'] = MeasuringStation.objects.all().count()
        return context


class MeasuringStationDetailView(generic.DetailView):
    """Show the details of a specific measuring station."""

    model = MeasuringStation
    template_name = 'sensors/measuringstation_detail.html'

    def get_context_data(self, **kwargs):
        """Get the context for the view, generic."""
        context = super().get_context_data(**kwargs)
        context['mode'] = "view"
        return context


class MeasuringStationEditView(UpdateView):
    """Edit a specific measuring station."""

    model = MeasuringStation
    fields = [
        "name",
        "description",
        "installed_sensors"
    ]
    success_url = "#"


class MeasuringStationDeleteView(DeleteView):
    """Delete a specific measuring station."""

    model = MeasuringStation
    success_url = reverse_lazy('sensors:stations_index')


class MeasuringStationCreateView(CreateView):
    """Create a new measuring station."""

    model = MeasuringStation
    fields = [
        "name",
        "description",
        "installed_sensors"
    ]

    def get_success_url(self):
        msg = "Measuring station successfully created. Details below."
        return reverse_lazy('sensors:stations_index')
    #success_url = reverse_lazy('sensors:station_detail', args=(self.object.id))


class ProbesList(generic.ListView):
    """Show the list of saved probe_drivers."""

    paginate_by = 10
    model = ProbeDriver
    template_name = 'sensors/probes_list.html'
    context_object_name = 'latest_probes_list'

    def get_context_data(self, **kwargs):
        """Get the context for the view, generic."""
        context = super().get_context_data(**kwargs)
        context['probes_count'] = ProbeDriver.objects.all().count()
        return context

    def get_queryset(self):
        """Return the last 20 probes."""
        return ProbeDriver.objects.order_by('name')[:20]


class SensorDetailView(generic.DetailView):
    """Show the details of a specific sensor."""

    model = Sensor
    template_name = 'sensors/sensor_detail.html'

    def get_context_data(self, **kwargs):
        """Get the context for the view, generic."""
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['last'] = Measure.objects.filter(sensor_id=context['sensor'].id).order_by("-ts")[0]
        context['probe'] = ProbeDriver.objects.get(name=context['sensor'].probe_driver)
        context['measures_count'] = Measure.objects.filter(sensor_id=context['sensor'].id).count()
        return context


class IndexView(generic.ListView):
    """View for the main landing page of the app."""

    template_name = 'sensors/index.html'
    context_object_name = 'latest_sensor_list'

    def get_context_data(self, **kwargs):
        """Get the context for the view, generic."""
        context = super().get_context_data(**kwargs)
        context['sensors_count'] = Sensor.objects.all().count()
        return context

    def get_queryset(self):
        """Return the last four saved sensors."""
        return Sensor.objects.order_by('-id')[:4]

sensors/templates/sensors/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Industrious by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>{% block title %}RPI Sensors Manager{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<meta name="description" content="sensors manager is a webapp to manage sensors and generate config files for rpi-sensors-fetcher clients" />
		<meta name="keywords" content="raspberry pi, sensor, django, manage, config, yaml" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a class="logo" href="{% url 'sensors:landing_index' %}">RPI sensors manager</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					{% block sidebar %}
					<li><a href="{% url 'admin:index' %}">Admin</a></li>
					<li><a href="{% url 'sensors:landing_index' %}">Home</a></li>
					<li><a href="{% url 'sensors:sensors_index' %}">Sensors list</a></li>
					<li><a href="{% url 'sensors:probes_index' %}">Supported probes</a></li>
					<li><a href="{% url 'sensors:stations_index' %}">Stations de mesure</a></li>
					{% endblock %}
				</ul>
			</nav>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					{% block banner_div %}
					<h1>Sensors Manager</h1>
					<p>Configure and manage your sensors on a raspberry pi to consult or insert into a database</p>
					{% endblock %}
				</div>
				{% block banner_vid %}
				<video autoplay loop muted playsinline src="{% static "images/vid_banner_shrimp.mp4" %}"></video>
				{% endblock %}
			</section>

			{% block main_body %}
		<!-- Highlights -->
			<section class="wrapper">
				<div class="inner">
					<header class="special">
						<h2>generate configuration files</h2>
						<p>Select the sensors you want to activate on a node, then generate
							 a config file directly usable with the sensors fetcher client on your raspberry pi nodes.</p>
					</header>
					<div class="highlights">
						<section>
							<div class="content">
								<header>
									<a href="#" class="icon fa-vcard-o"><span class="label">Icon</span></a>
									<h3>Configured sensors</h3>
								</header>
								<p>
									There are {{ sensors_count }} sensors configured as of now.
								</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="#" class="icon fa-files-o"><span class="label">Icon</span></a>
									<h3>Supported probes</h3>
								</header>
								<p>Many probes are supported.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="#" class="icon fa-floppy-o"><span class="label">Icon</span></a>
									<h3>Measures</h3>
								</header>
								<p>Many measures recorded.</p>
							</div>
						</section>
					</div>
				</div>
			</section>

		<!-- CTA -->
			<section id="cta" class="wrapper">
				<div class="inner">
					<h2>Use the data with Grafana</h2>
					<p>
						Once everything is setup, your nodes will collect data to your
						database of choice. You can then use grafana to create cool dashboards!
					</p>
				</div>
			</section>
			{% endblock %}
		<!-- Footer -->
		{% block footer %}
			<footer id="footer">
				<div class="inner">
					<div class="content">
						<section>
							<h4>Probes</h4>
							<ul class="alt">
								<ul class="plain">
									<li><a href="https://github.com/sarinkhan/rpi_sensors_manager"><i class="icon fa-github"></i>rpi_sensors_manager</a></li>
									<li><a href="https://github.com/sarinkhan/rpi-sensor-fetcher"><i class="icon fa-github"></i>rpi-sensor-fetcher</a></li>
								</ul>
							</ul>
						</section>
						<section>
							<h4>Github repos</h4>
							<ul class="plain">
								<li><a href="https://github.com/sarinkhan/rpi_sensors_manager"><i class="icon fa-github"></i>rpi_sensors_manager</a></li>
								<li><a href="https://github.com/sarinkhan/rpi-sensor-fetcher"><i class="icon fa-github"></i>rpi-sensor-fetcher</a></li>
							</ul>
						</section>
					</div>
					<div class="copyright">
						&copy; Untitled. Photos <a href="https://unsplash.co">Unsplash</a>, Video <a href="https://coverr.co">Coverr</a>.
					</div>
				</div>
			</footer>
			{% endblock %}

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/browser.min.js" %}"></script>
			<script src="{% static "assets/js/breakpoints.min.js" %}"></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

sensors/templates/sensors/index.html
{% extends "sensors/base.html" %}

{% block title %}RPI Sensors Manager - Home{% endblock %}

{% block banner_div %}
<h1>Sensors Manager</h1>
<p>Configure and manage your sensors on a raspberry pi to consult or insert into a database</p>
{% endblock %}




{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">
    <header class="special">
      <h2>generate configuration files</h2>
      <p>Select the sensors you want to activate on a node, then generate
         a config file directly usable with the sensors fetcher client on your raspberry pi nodes.</p>
    </header>
    <div class="highlights">
      <section>
        <div class="content">
          <header>
            <a href="{% url 'sensors:sensors_index' %}" class="icon fa-vcard-o"><span class="label">Icon</span></a>
            <h3>Configured sensors</h3>
          </header>
          <p>
            There are {{ sensors_count }} sensors configured as of now.
            <a href="{% url 'sensors:sensors_index' %}">View the sensors</a>
          </p>
        </div>
      </section>
      <section>
        <div class="content">
          <header>
            <a href="#" class="icon fa-files-o"><span class="label">Icon</span></a>
            <h3>Supported probes</h3>
          </header>
          <p>Many probes are supported.</p>
        </div>
      </section>
      <section>
        <div class="content">
          <header>
            <a href="#" class="icon fa-floppy-o"><span class="label">Icon</span></a>
            <h3>Measures</h3>
          </header>
          <p>Many measures recorded.</p>
        </div>
      </section>
    </div>
  </div>
</section>

<!-- CTA -->
<section id="cta" class="wrapper">
  <div class="inner">
    <h2>Use the data with Grafana</h2>
    <p>
      Once everything is setup, your nodes will collect data to your
      database of choice. You can then use grafana to create cool dashboards!
    </p>
  </div>
</section>
{% endblock %}

{% block footer %}
  <footer id="footer">
    <div class="inner">
      <div class="content">
        <section>
          <h4>Latest configured sensors</h4>
          <ul class="alt">
            {% if latest_sensor_list %}
                <ul>
                {% for sensor in latest_sensor_list %}
                    <li><a href="{% url 'sensors:sensor_detail' sensor.id %}">{{ sensor.name }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No sensor available.</p>
            {% endif %}
          </ul>
        </section>
        <section>
          <h4>Probes</h4>
          <ul class="alt">
            <ul class="plain">
              <li><a href="https://github.com/sarinkhan/rpi_sensors_manager"><i class="icon fa-github"></i>rpi_sensors_manager</a></li>
              <li><a href="https://github.com/sarinkhan/rpi-sensor-fetcher"><i class="icon fa-github"></i>rpi-sensor-fetcher</a></li>
            </ul>
          </ul>
        </section>
        <section>
          <h4>Github repos</h4>
          <ul class="plain">
            <li><a href="https://github.com/sarinkhan/rpi_sensors_manager"><i class="icon fa-github"></i>rpi_sensors_manager</a></li>
            <li><a href="https://github.com/sarinkhan/rpi-sensor-fetcher"><i class="icon fa-github"></i>rpi-sensor-fetcher</a></li>
          </ul>
        </section>
      </div>
      <div class="copyright">
        &copy; Untitled. Photos <a href="https://unsplash.co">Unsplash</a>, Video <a href="https://coverr.co">Coverr</a>.
      </div>
    </div>
  </footer>
  {% endblock %}

sensors/templates/sensors/measuringstation_confirm_delete.html
{% extends "sensors/base.html" %}

{% block title %}Delete station {{ measuringsation.name }}{% endblock %}

{% block banner_div %}
<h1>Delete a Station</h1>
<p><a href="{% url 'sensors:stations_index' %}">return to stations index</a></p>
{% endblock %}

{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">
  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input type="submit" value="Confirm">
  </form>
  <a href="{% url 'sensors:stations_index' %}">return to stations index</a>

  </div>
</section>

{% endblock %}

sensors/templates/sensors/measuringstation_detail.html
{% extends "sensors/base.html" %}

{% block title %}Station {{ station.name }}{% endblock %}

{% block banner_div %}
<h1>Station {{ measuringstation.name }}</h1>
<p>{{ measuringstation.description }}.</p>
{% endblock %}


{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">

    {% if msg %}<div class='imp_message'>{{ msg }}</div>{% endif %}

    <a href="{% url 'sensors:station_create' %}">add a station</a> |
    <a href="{% url 'sensors:station_delete' measuringstation.id %}">delete {{ measuringstation.name }}</a> |
    <a href="{% url 'sensors:station_update' measuringstation.id %}">edit {{ measuringstation.name }}</a>
    <p>Station ID : {{ measuringstation.id }}</p>
    <p>station name : {{ measuringstation.name }}</p>
    <p>Description :  <em>{{ measuringstation.description }}</em></p>

    <h4>sensors installed in this station</h4>
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>ID</th>
            <th>driver</th>
          </tr>
        </thead>
        <tbody>
        {% for sensor in measuringstation.installed_sensors.all %}
        <tr>
          <td><a href="{% url 'sensors:sensor_detail' sensor.id %}">{{ sensor.name }}</a></td>
          <td>{{ sensor.description }}</td>
          <td>{{ sensor.id }}</td>
          <td>{{ sensor.probe_driver.name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'sensors:stations_index' %}">return to stations index</a>

  </div>
</section>

{% endblock %}

sensors/templates/sensors/measuringstation_form.html
{% extends "sensors/base.html" %}

{% block title %}Edit station {{ measuringsation.name }}{% endblock %}

{% block banner_div %}
<h1>Edit the parameters</h1>
<p><a href="{% url 'sensors:stations_index' %}">return to stations index</a></p>
{% endblock %}

{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">

    {% if result %}<div class='imp_message'>station added successfully!</div>{% endif %}

    <h4>Enter station details</h4>
    <div class="table-wrapper">

      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save">
      </form>
    <a href="{% url 'sensors:stations_index' %}">return to stations index</a>

  </div>
</section>

{% endblock %}

sensors/templates/sensors/measuringstations_list.html
{% extends "sensors/base.html" %}

{% block title %}RPI Sensors Manager - Home{% endblock %}

{% block banner_div %}
<h1>List of measuring stations</h1>
<p> Measuring stations configured : {{ count }}.</p>
{% endblock %}




{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">

        <h4>List of the measuring stations</h4>
        <div class="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>ID</th>
              </tr>
            </thead>
            <tbody>
              {% for station in page_obj %}
                  <tr>
                    <td><a href="{% url 'sensors:station_detail' station.id %}">{{ station.name }}</a></td>
                    <td>{{ station.description }}</td>
                    <td>{{ station.id }}</td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>

        <a href="{% url 'sensors:station_create' %}">add a station</a>


  </div>
</section>

{% endblock %}

sensors/templates/sensors/probes_list.html
{% extends "sensors/base.html" %}

{% block title %}RPI Sensors Manager - Home{% endblock %}

{% block banner_div %}
<h1>List of supported probes</h1>
<p>There are {{ probes_count }} probes supported right now.</p>
{% endblock %}


{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">

        <h4>List of the supported probes</h4>
        <div class="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>driver name</th>
                <th>description</th>
                <th>unit</th>
                <th>min</th>
                <th>max</th>
              </tr>
            </thead>

            <tbody>
              {% for probe in page_obj %}
                  <tr>
                    <td>{{ probe.name }}</td>
                    <td>{{ probe.description }}</td>
                    <td>{{ probe.unit }} ({{ probe.unit_symbol }})</td>
                    <td>{{ probe.min_value }}</td>
                    <td>{{ probe.max_value }}</td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>

          <div class="pagination">
              <span class="step-links">
                  {% if page_obj.has_previous %}
                      <a href="?page=1">&laquo; first</a>
                      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>

                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}">next</a>
                      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
              </span>
          </div>

  </div>
</section>

{% endblock %}

sensors/templates/sensors/sensor_detail.html
{% extends "sensors/base.html" %}

{% block title %}Sensor {{ sensor.name }}{% endblock %}

{% block banner_div %}
<h1>Sensor {{ sensor.name }}</h1>
<p>{{ sensor.description }}.</p>
{% endblock %}




{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">
    <div class="table-wrapper">
      <table>
        <tbody>
        <tr>
          <td>ID</td>
          <td>{{ sensor.id }}</td>
        </tr>
        <tr>
          <td>name</td>
          <td>{{ sensor.name }}</td>
        </tr>
        <tr>
          <td>description</td>
          <td>{{ sensor.description }}</td>
        </tr>
        <tr>
          <td>driver</td>
          <td>{{ sensor.probe_driver.name }}</td>
        </tr>
        <tr>
          <td>last value</td>
          <td>{{ last.value }} {{ sensor.probe_driver.unit_symbol }}</td>
        </tr>
        <tr>
          <td>last measure timestamp</td>
          <td>{{ last.ts }}</td>
        </tr>
        <tr>
          <td>measure count</td>
          <td>{{ measures_count }}</td>
        </tr>
        <tr>
          <td>min possible value</td>
          <td>{{ sensor.probe_driver.min_value }} {{ sensor.probe_driver.unit_symbol }}</td>
        </tr>
        <tr>
          <td>max possible value</td>
          <td>{{ sensor.probe_driver.max_value }} {{ sensor.probe_driver.unit_symbol }}</td>
        </tr>

        <tr>
          <td>used by</td>
          <td>
            <ul>
            {% for station in sensor.measuringstation_set.all %}
                <li> <a href="{% url 'sensors:station_detail' station.id %}">{{ station.name }}</a></li>
            {% endfor %}
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
    </div>

    <a href="{% url 'sensors:sensors_index' %}">return to sensors index</a>

  </div>
</section>

{% endblock %}

sensors/templates/sensors/sensors_list.html
{% extends "sensors/base.html" %}

{% block title %}RPI Sensors Manager - Home{% endblock %}

{% block banner_div %}
<h1>List of configured sensors</h1>
<p>There are {{ sensors_count }} sensors configured as of now.</p>
{% endblock %}




{% block main_body %}
<!-- Highlights -->
<section class="wrapper">
  <div class="inner">




        <h4>List of the sensors</h4>
        <div class="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>ID</th>
              </tr>
            </thead>
            <tbody>
              {% for sensor in page_obj %}
                  <tr>
                    <td><a href="{% url 'sensors:sensor_detail' sensor.id %}">{{ sensor.name }}</a></td>
                    <td>{{ sensor.description }}</td>
                    <td>{{ sensor.id }}</td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>


  </div>
</section>

{% endblock %}